### ISSUE TITLE
Incompatible with the newest Tower app?

### ISSUE THREAD

**Issue by egantz** [cjlucas/tower-alfred-workflow#19]
Hi! I tried to figure why the workflow stopped working and I realized I have recently upgraded my Tower app. so I did some digging into the debug mode and figure it looks for bookmarks-v2.plist

Will it be possible to make it compatible with the newest tower app? this workflow is greatly useful!

Many thanks

**Comment by hechen** [comment]
@egantz 

Because bookmark folder of Tower 3 has changed. It is located in '~/Library/Application Support/com.fournova.Tower3/bookmarks-v2.plist' now.

You can edit the workflow directly. What you need to do is just fix bookmark folder from Tower2 to Tower3. 


![capto_capture 2018-11-05_02-55-52_pm2](https://user-images.githubusercontent.com/2241096/47982643-75ad9480-e10b-11e8-9dcd-b825c69cd5bd.png)

**Comment by egantz** [comment]
Worked! thanks so much @hechen 🏆
